<?xml version="1.0" encoding="windows-1251"?>
<definitions xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
             xmlns:ns="urn:mytargetns" targetNamespace="urn:mytargetns">
    <message name="MySoapMsg">
        <part name="request" type="ns:MyRequestData"/>
    </message>
    <portType name="My_SoapPortType">
        <operation name="MyOperation">
            <input message="ns:MySoapMsg"/>
            <output message="ns:MySoapMsg"/>
        </operation>
    </portType>
    <binding name="My_SoapBinding" type="ns:My_SoapPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="MyOperation">
            <soap:operation soapAction="urn:#MyOperation"/>
            <input>
                <soap:body use="literal" namespace="urn:mytargetns"/>
            </input>
            <output>
                <soap:body use="literal" namespace="urn:mytargetns"/>
            </output>
        </operation>
    </binding>
    <service name="My_Service">
        <port name="My_SoapPort" binding="ns:My_SoapBinding">
            <soap:address location="http://10.10.12.30/result/SOAP_samples/MySOAPServer.php"/>
        </port>
    </service>
</definitions>